apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/silverdeath366/devops-platform
    targetRevision: main
    path: helm/charts/notification
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
