name: CI/CD - Notification Service

on:
  push:
    paths:
      - 'services/notification/**'
      - '.github/workflows/notification-ci.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: silverdeath366/notification
      IMAGE_TAG: v2
      SERVICE_PATH: services/notification

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install test dependencies
      run: |
        pip install --upgrade pip
        pip install -r $SERVICE_PATH/requirements.txt
        pip install pytest httpx

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/services" >> $GITHUB_ENV

    - name: Run Tests
      run: |
        pytest $SERVICE_PATH/tests

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker image
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG ./$SERVICE_PATH
        docker push $IMAGE_NAME:$IMAGE_TAG
