name: CI/CD - User Service

on:
  push:
    paths:
      - 'services/user/**'
      - '.github/workflows/user-ci.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: silverdeath366/user
      HELM_CHART_PATH: helm/charts/user
      VALUES_FILE: helm/charts/user/values.yaml

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract short SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r services/user/requirements.txt
        pip install pytest httpx

    - name: Run Tests
      run: |
        pytest services/user/tests

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker image
      run: |
        docker build -t $IMAGE_NAME:${{ steps.vars.outputs.sha_short }} ./services/user
        docker push $IMAGE_NAME:${{ steps.vars.outputs.sha_short }}

    - name: Update Helm values.yaml with SHA tag
      run: |
        sed -i 's|tag:.*|tag: "${{ steps.vars.outputs.sha_short }}"|' $VALUES_FILE
